User:
    type: entity
    table: users
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        salutation:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: SALUTATION
        firstname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: FIRSTNAME
        lastname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: LASTNAME
        login:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LOGIN
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: EMAIL
        telephone:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: TELEPHONE
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: PASSWORD
        adresse:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ADRESSE
        postalcode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: POSTALCODE
    lifecycleCallbacks: {  }
